"""Initial migration

Revision ID: 087a3185c54b
Revises: 
Create Date: 2025-08-12 18:42:32.565925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '087a3185c54b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('COMPANY', 'ORGANIZATIN_NAME', 'DEPARTMENT', 'TEAM', 'GROUP', name='organizationtype'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('COMPANY', 'ORGANIZATIN_NAME', 'DEPARTMENT', 'TEAM', 'GROUP', name='organizationtype'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###