"""add defect status history table

Revision ID: 1965c614beb7
Revises: 087a3185c54b
Create Date: 2025-08-13 16:20:13.303673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1965c614beb7'
down_revision = '087a3185c54b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defect_status_history',
    sa.Column('id', sa.String(length=25), nullable=False, comment='历史记录ID，格式：H + 雪花算法ID'),
    sa.Column('defect_id', sa.String(length=25), nullable=False, comment='缺陷ID'),
    sa.Column('old_status', sa.Enum('NEW', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'VERIFIED', 'CLOSED', 'REOPENED', name='defectstatus'), nullable=True, comment='变更前状态'),
    sa.Column('new_status', sa.Enum('NEW', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'VERIFIED', 'CLOSED', 'REOPENED', name='defectstatus'), nullable=False, comment='变更后状态'),
    sa.Column('changed_by', sa.String(length=25), nullable=False, comment='变更人ID'),
    sa.Column('changed_at', sa.DateTime(), nullable=True, comment='变更时间'),
    sa.Column('comment', sa.Text(), nullable=True, comment='变更备注'),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['defect_id'], ['defects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defect_status_history_id'), 'defect_status_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_defect_status_history_id'), table_name='defect_status_history')
    op.drop_table('defect_status_history')
    # ### end Alembic commands ###