"""add_manager_foreign_key

Revision ID: 5aeb1cb303e4
Revises: b7946140c2a7
Create Date: 2025-07-24 18:19:27.232741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aeb1cb303e4'
down_revision = 'b7946140c2a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_projects_manager_id', 'users', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('fk_projects_manager_id', type_='foreignkey')
    # ### end Alembic commands ###