"""Add organization_id to users table

Revision ID: 8af1b16a21b6
Revises: e4da776c46be
Create Date: 2025-07-21 19:06:21.020451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8af1b16a21b6'
down_revision = 'e4da776c46be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """升级数据库结构"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """降级数据库结构"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###