"""add_handler_fields_to_defects

Revision ID: 9b831bda5b05
Revises: b5bc2ef51c55
Create Date: 2025-08-14 18:28:33.050504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b831bda5b05'
down_revision = 'b5bc2ef51c55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.alter_column('handler_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('severity',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('TRIVIAL', 'MINOR', 'MAJOR', 'IMPORTANT', 'CRITICAL', 'URGENT', 'BLOCKER', name='defectseverity'),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_defects_handler_id', 'users', ['handler_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.drop_constraint('fk_defects_handler_id', type_='foreignkey')
        batch_op.alter_column('severity',
               existing_type=sa.Enum('TRIVIAL', 'MINOR', 'MAJOR', 'IMPORTANT', 'CRITICAL', 'URGENT', 'BLOCKER', name='defectseverity'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
        batch_op.alter_column('handler_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))

    # ### end Alembic commands ###