"""add_comments_table

Revision ID: ad037af086b1
Revises: 1965c614beb7
Create Date: 2025-08-13 16:32:25.579446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad037af086b1'
down_revision = '1965c614beb7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.String(length=25), nullable=False, comment='评论ID，格式：C + 雪花算法ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='评论内容'),
    sa.Column('target_type', sa.Enum('DEFECT', 'TASK', 'PROJECT', name='commenttargettype'), nullable=False, comment='评论目标类型'),
    sa.Column('target_id', sa.String(length=25), nullable=False, comment='评论目标ID'),
    sa.Column('author_id', sa.String(length=25), nullable=False, comment='评论作者ID'),
    sa.Column('parent_id', sa.String(length=25), nullable=True, comment='父评论ID，用于回复功能'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###