"""add_document_table

Revision ID: b5bc2ef51c55
Revises: ad037af086b1
Create Date: 2025-08-14 11:29:38.800298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5bc2ef51c55'
down_revision = 'ad037af086b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.String(length=27), nullable=False, comment='文档ID，格式：DOC + 雪花算法ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='文档/文件夹名称'),
    sa.Column('type', sa.Enum('FOLDER', 'DOCUMENT', name='documenttype'), nullable=False, comment='类型：文件夹或文档'),
    sa.Column('parent_id', sa.String(length=27), nullable=True, comment='父级文件夹ID，根目录为NULL'),
    sa.Column('file_type', sa.String(length=50), nullable=True, comment='文件类型（仅文档类型）'),
    sa.Column('file_size', sa.BigInteger(), nullable=True, comment='文件大小（字节，仅文档类型）'),
    sa.Column('file_path', sa.String(length=500), nullable=True, comment='文件存储路径（MinIO路径）'),
    sa.Column('mime_type', sa.String(length=100), nullable=True, comment='MIME类型'),
    sa.Column('bucket_name', sa.String(length=100), nullable=True, comment='MinIO存储桶名称'),
    sa.Column('object_key', sa.String(length=500), nullable=True, comment='MinIO对象键'),
    sa.Column('checksum', sa.String(length=64), nullable=True, comment='文件校验和（MD5）'),
    sa.Column('description', sa.Text(), nullable=True, comment='文档描述'),
    sa.Column('created_by', sa.String(length=25), nullable=False, comment='创建人ID'),
    sa.Column('updated_by', sa.String(length=25), nullable=True, comment='更新人ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否已删除'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('deleted_by', sa.String(length=25), nullable=True, comment='删除人ID'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_id'))

    op.drop_table('documents')
    # ### end Alembic commands ###