"""Initial migration with priority and manager_id

Revision ID: b7946140c2a7
Revises: 
Create Date: 2025-07-24 17:56:45.533181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7946140c2a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 分别添加列以避免循环依赖
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='projectpriority'), nullable=True))
    
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager_id', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key('fk_projects_manager_id', 'users', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'manager_id')
    op.drop_column('projects', 'priority')
    op.create_table('tasks_new',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=11), nullable=True),
    sa.Column('priority', sa.VARCHAR(length=6), nullable=True),
    sa.Column('task_type', sa.VARCHAR(length=13), nullable=True),
    sa.Column('due_date', sa.DATETIME(), nullable=True),
    sa.Column('estimated_hours', sa.FLOAT(), nullable=True),
    sa.Column('actual_hours', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('project_id', sa.BIGINT(), nullable=True),
    sa.Column('assignee_id', sa.BIGINT(), nullable=True),
    sa.Column('reporter_id', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_new_title'), 'tasks_new', ['title'], unique=False)
    op.create_index(op.f('ix_tasks_new_id'), 'tasks_new', ['id'], unique=False)
    op.create_table('projects_new',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=9), nullable=True),
    sa.Column('priority', sa.VARCHAR(length=6), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('creator_id', sa.BIGINT(), nullable=True),
    sa.Column('organization_id', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_new_name'), 'projects_new', ['name'], unique=False)
    op.create_index(op.f('ix_projects_new_id'), 'projects_new', ['id'], unique=False)
    op.create_table('task_comments_new',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('task_id', sa.BIGINT(), nullable=True),
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_comments_new_id'), 'task_comments_new', ['id'], unique=False)
    op.create_table('task_attachments_new',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), nullable=False),
    sa.Column('file_size', sa.INTEGER(), nullable=True),
    sa.Column('content_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('uploaded_at', sa.DATETIME(), nullable=True),
    sa.Column('task_id', sa.BIGINT(), nullable=True),
    sa.Column('uploaded_by', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_attachments_new_id'), 'task_attachments_new', ['id'], unique=False)
    op.create_table('organizations_new',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_new_name'), 'organizations_new', ['name'], unique=1)
    op.create_index(op.f('ix_organizations_new_id'), 'organizations_new', ['id'], unique=False)
    op.create_table('project_members_new',
    sa.Column('project_id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=7), nullable=True),
    sa.Column('joined_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects_new.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_new.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.create_table('users_new',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('role', sa.VARCHAR(length=7), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('organization_id', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_new_username'), 'users_new', ['username'], unique=1)
    op.create_index(op.f('ix_users_new_id'), 'users_new', ['id'], unique=False)
    op.create_index(op.f('ix_users_new_email'), 'users_new', ['email'], unique=1)
    op.create_table('organization_members_new',
    sa.Column('organization_id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=7), nullable=True),
    sa.Column('joined_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations_new.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users_new.id'], ),
    sa.PrimaryKeyConstraint('organization_id', 'user_id')
    )
    # ### end Alembic commands ###